apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      application: loadgen
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: loadgen
    spec:
      containers:
      - image: quay.io/gordons/address-demo-loadgen
        imagePullPolicy: IfNotPresent
        name: upper
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: connect-config
