apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pink-reverse
spec:
  replicas: 1
  selector:
    matchLabels:
      application: pink-reverse
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: pink-reverse
    spec:
      containers:
      - env:
        - name: COLOUR
          value: pink
        - name: OPERATION
          value: reverse
        - name: GROUP
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/gordons/address-demo-service
        imagePullPolicy: IfNotPresent
        name: reverse
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: connect-config
