apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: purple-upper
spec:
  replicas: 1
  selector:
    matchLabels:
      application: purple-upper
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: purple-upper
    spec:
      containers:
      - env:
        - name: COLOUR
          value: purple
        - name: OPERATION
          value: upper
        - name: GROUP
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/gordons/address-demo-service
        imagePullPolicy: IfNotPresent
        name: upper
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: connect-config
